apiVersion: v1
kind: Service
metadata:
  name: simple-jwt-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: simple-jwt-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-jwt-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: simple-jwt-api
  template:
    metadata:
      labels:
        app: simple-jwt-api
    spec:
      containers:
        - name: simple-jwt-api
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig
# metadata:
#   name: simple-jwt-api
#   region: eu-north-1
# nodeGroups:
#   - name: ng-1
#     instanceType: t2.nano
#     desiredCapacity: 10
#     volumeSize: 80
#     ssh:
#       allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
#   - name: ng-2
#     instanceType: t2.nano
#     desiredCapacity: 2
#     volumeSize: 100
#     ssh:
#       publicKeyPath: ~/.ssh/ec2_id_rsa.pub
